### ISSUE TITLE
Is this similar to the ideas in the M5nr paper ?

### ISSUE THREAD

**Issue by sebhtml** [sjackman/uniqtag#1]
Is this similar to [M5nr](http://www.biomedcentral.com/1471-2105/13/141) in the sense that sequence names are determined using their content ?

**Comment by sjackman** [comment]
Yes. I hadn't read this paper. Thanks for pointing me to it. A cryptographic hash function by design changes the hash value for small perturbations of the input, and the goal with UniqTag was to design a hash function that does not change for small perturbations of the input.

**Comment by sebhtml** [comment]
Thank you.
