### ISSUE TITLE
Release says 1.0 but --version reports 0.1.0

### ISSUE THREAD

**Issue by tseemann** [sjackman/uniqtag#2]
```
uniqtag --version
uniqtag 0.1.0
```

**Comment by sjackman** [comment]
Fixed by https://github.com/sjackman/uniqtag/commit/34165351c61d865da8c3135e9bbc5a80d27d40d6. Thanks, Torsten!

**Comment by sjackman** [comment]
I've also tagged release `1.0.0` https://github.com/sjackman/uniqtag/releases

**Comment by tseemann** [comment]
LOL that's a sneaky release :)
